### ISSUE TITLE
npm start: TypeError: Can't add property _eventsCount, object is not extensible

### ISSUE THREAD

**Issue by ramukima** [corenova/yang-cord#4]
git clone ..; npm install; npm start

events.js:221
    target._eventsCount = 0;
                        ^
TypeError: Can't add property _eventsCount, object is not extensible
    at _addListener (events.js:221:25)
    at Model.addListener (events.js:270:10)
    at EventEmitter.<anonymous> (../yang-cord/lib/api/server.js:14:17)

**Comment by ramukima** [comment]
This actually relates to yang-js project. I patched it like below to make it work locally -

https://github.com/corenova/yang-js/blob/master/src/yang.coffee#L29

```
      '_events':   writable: true
      '_eventsCount':   writable: true
```

**Comment by ramukima** [comment]
Closing as duplicate - https://github.com/corenova/yang-js/issues/21
